### PR TITLE
added support for Qt6

### PR DESCRIPTION
**Pull request by zaxo7**
i edited the header files to support Qt6

### CODE REVIEW

**Comment by oleavr** [comment]
Thanks! (And apologies for the delay!) Is there any harm in also doing this on Qt < 6?

**Comment by zaxo7** [comment]
no,
by adding (#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)) it doesn't affect Qt < 6
i tested it on both version, it works fine
thanks,

**Comment by zaxo7** [comment]
any news ?

**Comment by oleavr** [comment]
So sorry for the delay! 😬 In the future feel free to poke me on Telegram (nick: oleavr) -- my GitHub notifications are a mess 😪

Thanks a lot for this great contribution! 🔥

**Pull request merged**
